"use client"
// Auto-generated by boneyard vite plugin — do not edit
import { registerBones } from 'boneyard-js/react'

import _footer_github_activity from './footer-github-activity.bones.json'

registerBones({
  "footer-github-activity": _footer_github_activity,
})
