"use client"
// Auto-generated by boneyard vite plugin — do not edit
import { registerBones } from 'boneyard-js/react'

import _github_activity_feed from './github-activity-feed.bones.json'

registerBones({
  "github-activity-feed": _github_activity_feed,
})
